#  读取文件
fileClass:
  filePath:
    #     神州联保加密公钥
    publicKey1: C:\Users\ZJY\Desktop\key\shenzhou\publicKey.txt

#      加解密的公钥和私钥
    publicKey2: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDiD2uNT9dlLqSap7oMrq83SVvKFjo8t5lBxz+B3P4cBnwwW9CZw3UHmtI+bsQM/RJkWvXN8AsuFatRxFiNuUv+5f8cbNABVzf/DaEt7Sc/I0xx5OXeJY8FKAgdjYYwP8dpCrk88NxWBng9tLSkr5iJ/XtAkOgi/w7Vsxrxx6El5QIDAQAB
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAOIPa41P12UupJqnugyurzdJW8oWOjy3mUHHP4Hc/hwGfDBb0JnDdQea0j5uxAz9EmRa9c3wCy4Vq1HEWI25S/7l/xxs0AFXN/8NoS3tJz8jTHHk5d4ljwUoCB2NhjA/x2kKuTzw3FYGeD20tKSvmIn9e0CQ6CL/DtWzGvHHoSXlAgMBAAECgYEAvDzy5hzR02NflZiNB/p91J+1WzXfEKghafCsJUsMHfIYf3w025UyYj69S1eY0Of65K4JeI6mAJ3ypofE5V6is/HFu5X2HuZ67Dwm4QOJFORft3FVfc2AaYPQr7ZmhkD6WDTsoyIFIEd3H0wcvOmED39K/3cANzlg3zaLH8bDfgECQQD007UQFjHszPTEIroLLsuHta0CJIMxII4EcLYrZKuBUGhtRWoeHcTR8FAbMFcuC4AQ0nUujCgjWtVDmGYvD9WhAkEA7GB2aZvbx0rYyp1VRFdlfYHPcfDGx1SrUjqZK0XOMH36JRN847S+JIclVTvUoqCuHT820ZOC8o625sOlbOghxQJBAIW3Q0L//FCLOHwPQ3FsI3mBfnaXHpgsYaSHMtfMaed81SwpJ2Y/eAn5qKbQ5iyd11pYt+uuXRXCPIxopha6HUECQGUIZhSF1c69IySXUxa+9FZM4colzBDvE7s16LoiQBth/UVTqxH48zzRtxdTV3ObklBV8KxrjJD4hxzjixWdsrECQDz0O619OiE7ecP2ENcSG1bmdzGmnC1atMBnEUhmEloxYrRVMdCN8dJRiWJ7Bp+kp749Wtu9gMp0VT1YfMuURCg=
#    publicKey2: C:\Users\ZJY\Desktop\key\key\publicKey.txt
#    privateKey: C:\Users\ZJY\Desktop\key\key\privateKey.txt


LianBaoUrl:
  #  神州联保url
  ShenZhou: http://ntest.szlb.cc/api/papi.php/

#  快递鸟
KDNiao:
  EBusinessID: 1575645
  APIKey: 6709bebc-7ac3-4208-a5fc-80fef03bd36c
#  url: http://api.kdniao.com/api/OOrderService  #  正式环境
  url: http://testapi.kdniao.com:8081/api/oorderservice  #  测试环境
#  url: http://sandboxapi.kdniao.com:8080/kdniaosandbox/gateway/exterfaceInvoke.json  #  沙箱测试环境


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usertest?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations:
